### ISSUE TITLE
Fabric server timed out due to coroutine

### ISSUE THREAD

**Issue by TheAyes** [FabricMC/fabric-language-kotlin#70]
Made a server that runs with a few mods using kotlin however the server get's timed out if I try stopping it.
```
[08:25:20] [Server thread/ERROR]: Exception stopping the server
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 300000 ms
        at kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:184) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
        at kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:154) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
        at kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:502) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
        at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:279) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
        at kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:108) ~[org_jetbrains_kotlinx_kotlinx-coe-jvm-1.6.1-d112832ca8065f4e.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by jakobkmar** [comment]
This is an issue with a mod (written in Kotlin) you installed, and not fabric-language-kotlin itself.

This mod seems to use timeouts incorrectly.

**Comment by modmuss50** [comment]
👋 We use the issue tracker exclusively for final bug reports and feature requests. However, this issue appears to be better suited for either a [discussion thread](https://github.com/orgs/FabricMC/discussions), or a message on [our discord server](https://discord.gg/v6v4pMv). Please post your request on one of these, and the conversation can continue there.
